title: <p align="center"> Bhargava teja Maddula </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/bhargavateja-maddula-9088ab151/">LinkedIn</a> |
  <a href="https://github.com/Bhargava1999/">GitHub</a>
  
  <br>   
  I'm working as SRE Devoloper on cloud devolopment and customer facing related problems.
  Working with IBM Research on IBM GEN CLOUD.
  Working in OverlayOperation for 2 years.
  <br>
  </p>



theme: jekyll-theme-minimal
